apiVersion: v1
kind: Pod
metadata:
  name: employee-api-pod-created
  labels:
    app: web
spec:
  containers:
    - name: web-ctr
      image: 991080/employee_api_repo_docker:dempapi
      ports:
        - containerPort: 8089